# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    - name: Publishing flist
      uses: threefoldtech/publish-flist@master
      with:
        action: publish
        name: demo-from-action.flist
        token: ${{ secrets.HUB_TOKEN }}
